pipeline:
  run_tests:
    image: node:8
    commands:
      - npm install -s
      - npm run test
  publish_image:
    image: plugins/docker
    repo: iteam1337/izone
    username:  ${DOCKER_USER}
    password: ${DOCKER_PASS}
    email:  ${DOCKER_EMAIL}
    tags: latest
    when:
      branch: develop
  redeploy_service:
    image: peloton/drone-rancher
    url: http://192.168.100.41:8080
    access_key: ${RANCHER_KEY}
    secret_key: ${RANCHER_SECRET}
    service: Izone/izone-rest
    docker_image: iteam1337/izone:latest
    confirm: true
    timeout: 120
    when:
      branch: develop
