pipeline:
  test:
    image: node:7
    commands:
      - npm install -s
      - npm run test
      - npm run standard
  docker:
    image: plugins/docker
    repo: iteam1337/izone
    username:  ${DOCKER_USERNAME}
    password: ${DOCKER_PASS}
    email:  ${DOCKER_EMAIL}
    tags: latest
  rancher:
    image: peloton/drone-rancher
    url: http://192.168.100.41:8080
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: Izone/izone-rest
    docker_image: iteam1337/izone:latest
    confirm: true
    timeout: 120
