pipeline:
  test:
    image: node:7
    commands:
      - npm i > /dev/null 2>&1
      - npm run test
  docker:
    image: plugins/docker
    repo: iteam1337/izone
    username: ilix
    password: ${DOCKER_PASS}
    email: src@ilix.se
    tags: latest
    build_args:
     - A_VAR=${SOME_VALUE}
