pipeline:
  test:
    image: node:7
    commands:
      - npm install > /dev/null 2>&1
      - npm run test
  docker:
    image: plugins/docker
    repo: iteam1337/izone
    username: ilix
    password: ${DOCKER_PASS}
    email: src@ilix.se
    tags: latest
    build_args:
     - A_VAR=${SOME_VALUE}
  rancher:
    image: peloton/drone-rancher
    url: https://rancher.iteam.life
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: Izone/izone-rest
    docker_image: iteam1337/izone:latest
    confirm: true
